# Generated by Django 4.2.15 on 2025-11-21 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.IntegerField(choices=[(0, 'BENIGN'), (1, 'DDoS'), (2, 'FTP-Patator'), (3, 'SSH-Patator'), (4, 'DoS Hulk'), (5, 'DoS GoldenEye'), (6, 'DoS Slowloris'), (7, 'DoS Slowhttptest'), (8, 'Heartbleed'), (9, 'Web Attack – Brute Force'), (10, 'Web Attack – XSS'), (11, 'Web Attack – SQL Injection'), (12, 'Infiltration')], default=0)),
                ('attack_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('destination_port', models.FloatField()),
                ('flow_iat_min', models.FloatField()),
                ('init_win_bytes_forward', models.FloatField()),
                ('flow_duration', models.FloatField()),
                ('total_length_of_fwd_packets', models.FloatField()),
                ('init_win_bytes_backward', models.FloatField()),
                ('flow_bytes_s', models.FloatField()),
                ('fwd_iat_min', models.FloatField()),
                ('bwd_packets_s', models.FloatField()),
                ('fwd_packet_length_max', models.FloatField()),
                ('bwd_iat_total', models.FloatField()),
                ('fin_flag_count', models.FloatField()),
                ('flow_packets_s', models.FloatField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('scenario_name', models.CharField(default='Unknown', max_length=200)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='detected', max_length=20)),
                ('investigation_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FirewallConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firewall_enabled', models.BooleanField(default=True)),
                ('auto_block_enabled', models.BooleanField(default=True)),
                ('block_duration', models.IntegerField(default=3600)),
                ('max_attempts', models.IntegerField(default=5)),
                ('whitelist_ips', models.TextField(blank=True, help_text='Comma-separated IP addresses')),
                ('block_threshold', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firewall Configuration',
                'verbose_name_plural': 'Firewall Configurations',
            },
        ),
        migrations.CreateModel(
            name='MonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('admin_emails', models.TextField(help_text='Comma-separated list of admin emails')),
                ('email_threshold', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('monitoring_enabled', models.BooleanField(default=True)),
                ('auto_block_enabled', models.BooleanField(default=False)),
                ('confidence_threshold', models.FloatField(default=0.7)),
                ('max_alerts_per_hour', models.IntegerField(default=10)),
                ('cooldown_period', models.IntegerField(default=300, help_text='Seconds between similar alerts')),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitoring Configuration',
                'verbose_name_plural': 'Monitoring Configurations',
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_requests', models.IntegerField(default=0)),
                ('attacks_detected', models.IntegerField(default=0)),
                ('false_positives', models.IntegerField(default=0)),
                ('system_load', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='System is under maintenance. Please try again later.')),
                ('maintenance_start', models.DateTimeField(blank=True, null=True)),
                ('maintenance_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Maintenance',
                'verbose_name_plural': 'System Maintenance',
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(default='Security Alert', max_length=50)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('metadata', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attack_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cyberattack.attacklog')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('block_ip', 'Block IP Address'), ('block_attack', 'Block Attack Type'), ('rate_limit', 'Rate Limiting'), ('geo_block', 'Geographic Block')], max_length=20)),
                ('rule_value', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.IntegerField(choices=[(0, 'BENIGN'), (1, 'DDoS'), (2, 'FTP-Patator'), (3, 'SSH-Patator'), (4, 'DoS Hulk'), (5, 'DoS GoldenEye'), (6, 'DoS Slowloris'), (7, 'DoS Slowhttptest'), (8, 'Heartbleed'), (9, 'Web Attack – Brute Force'), (10, 'Web Attack – XSS'), (11, 'Web Attack – SQL Injection'), (12, 'Infiltration')])),
                ('attack_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('source_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('os_info', models.CharField(blank=True, max_length=200)),
                ('browser_info', models.CharField(blank=True, max_length=200)),
                ('device_type', models.CharField(blank=True, max_length=100)),
                ('screen_resolution', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('isp', models.CharField(blank=True, max_length=200)),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('block_duration', models.IntegerField(default=3600)),
                ('destination_port', models.FloatField()),
                ('flow_bytes_s', models.FloatField()),
                ('flow_packets_s', models.FloatField()),
                ('firewall_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyberattack.firewallrule')),
            ],
            options={
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['source_ip'], name='cyberattack_source__6c64d9_idx'), models.Index(fields=['blocked_at'], name='cyberattack_blocked_1d22ba_idx'), models.Index(fields=['attack_type'], name='cyberattack_attack__c65097_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='attacklog',
            index=models.Index(fields=['timestamp'], name='cyberattack_timesta_e394c8_idx'),
        ),
        migrations.AddIndex(
            model_name='attacklog',
            index=models.Index(fields=['attack_type'], name='cyberattack_attack__693b15_idx'),
        ),
        migrations.AddIndex(
            model_name='attacklog',
            index=models.Index(fields=['severity'], name='cyberattack_severit_69a5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='attacklog',
            index=models.Index(fields=['status'], name='cyberattack_status_63c37f_idx'),
        ),
    ]
